name: ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_storage: ^11.5.3
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  provider: ^6.1.1
  stylish_bottom_bar: ^1.0.3
  google_maps_flutter: ^2.0.10
  geocoding: ^2.0.1
  location: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true